### ISSUE TITLE
Error when executing shell script.

### ISSUE THREAD

**Issue by leeouho** [MilhouseVH/bcmstat#10]
Thank you for sharing a good code.
Could you suggest a solution?
input => ./bcmstat.sh xgpd10
Traceback (most recent call last):
  File "./bcmstat.sh", line 1619, in <module>
    main(sys.argv[1:])
  File "./bcmstat.sh", line 1481, in main
    commands = vcgencmd("commands")[1:-1].split(", ")
  File "./bcmstat.sh", line 347, in vcgencmd
    return grep("", runcommand("%s %s" % (VCGENCMD, args)), 1, split_char="=")
  File "./bcmstat.sh", line 318, in runcommand
    return subprocess.check_output(command.split(" "), stderr=subprocess.STDOUT)[:-1]
  File "/usr/lib/python2.7/subprocess.py", line 212, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
![image](https://user-images.githubusercontent.com/25336180/43824595-62a74f12-9b2d-11e8-8b02-0120d25fe176.png)

**Comment by MilhouseVH** [comment]
Closing, due to lack of requested information.
