### ISSUE TITLE
Crash of bcmstat v 0.3.8

### ISSUE THREAD

**Issue by paulcrawford** [MilhouseVH/bcmstat#4]
bcmstat crashed the other day with the following output:

Traceback (most recent call last):
  File "/home/daco/bin/bcmstat.sh", line 1433, in <module>
    main(sys.argv[1:])
  File "/home/daco/bin/bcmstat.sh", line 1395, in main
    getBCM283X(BCM)
  File "/home/daco/bin/bcmstat.sh", line 495, in getBCM283X
    [int(vcgencmd("measure_clock arm")),
  File "/home/daco/bin/bcmstat.sh", line 301, in vcgencmd
    return grep("", runcommand("%s %s" % (VCGENCMD, args)), 1, split_char="=")
  File "/home/daco/bin/bcmstat.sh", line 270, in runcommand
    return subprocess.check_output(command.split(" "), stderr=subprocess.STDOUT).decode("utf-8")[:-1]
  File "/usr/lib/python3.5/subprocess.py", line 629, in check_output
    *_kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 696, in run
    with Popen(_popenargs, **kwargs) as process:
  File "/usr/lib/python3.5/subprocess.py", line 950, in **init**
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1544, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/vc/bin/vcgencmd'

I have never seen a crash in bcmstat before. Do you think the problem is with my side or the bcmstat side?

Thanks,

Paul Crawford

**Comment by MilhouseVH** [comment]
It looks like `/opt/vc/bin/vcgencmd` is unavailable at the time it was required, while querying `measure_clock arm`, which is the first `vcgencmd`-related query whenever `bcmstat.sh` wakes up.

Were you upgrading your firmware (using either `apt-get` or `rpi-update`) while running `bcmstat.sh`, as this might conceivably cause `vcgencmd` to be replaced/overwritten leaving it momentarily unavailable to processes such as `bcmstat.sh`.
